"use client";

import { FormEvent, useEffect, useState } from "react";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import {
  ArrowDownRight, ArrowUpRight, BarChart3, BrainCircuit, Check, CheckCircle2,
  ChevronRight, Code2, Download, Github, GraduationCap, Linkedin, Mail, MapPin,
  Menu, Moon, Phone, Send, Sparkles, Sun, Wrench, X,
} from "lucide-react";
import {
  certifications, education, experience, focusAreas, navItems, profile,
  projects, publication, skillGroups, Project,
} from "@/data";

const skillIcons = { code: Code2, brain: BrainCircuit, chart: BarChart3, tool: Wrench };

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <motion.div initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ duration: 0.58, delay, ease: [0.22, 1, 0.36, 1] }} className={className}>{children}</motion.div>;
}

function SectionIntro({ index, eyebrow, title, copy }: { index: string; eyebrow: string; title: string; copy: string }) {
  return <div className="section-intro"><div><p className="eyebrow"><span>{index}</span>{eyebrow}</p><h2 className="font-display mt-4 max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h2></div><p className="max-w-md text-sm leading-7 text-muted lg:pb-1">{copy}</p></div>;
}

function ThemeToggle() {
  const [dark, setDark] = useState(false);
  useEffect(() => { const stored = localStorage.getItem("theme"); const next = stored ? stored === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches; setDark(next); document.documentElement.classList.toggle("dark", next); }, []);
  const toggle = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); localStorage.setItem("theme", next ? "dark" : "light"); };
  return <button onClick={toggle} aria-label={`Switch to ${dark ? "light" : "dark"} mode`} className="icon-button">{dark ? <Sun size={17} /> : <Moon size={17} />}</button>;
}

function Header() {
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState("about");
  useEffect(() => { const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActive(visible.target.id); }, { rootMargin: "-25% 0px -60% 0px", threshold: [0.05, 0.2, 0.5] }); navItems.forEach(({ href }) => { const element = document.querySelector(href); if (element) observer.observe(element); }); return () => observer.disconnect(); }, []);
  return <header className="site-header"><div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between px-5 sm:px-8"><a href="#top" className="brand focus-ring"><span className="brand-mark">DA</span><span>didar ali</span></a><nav className="hidden items-center gap-1 md:flex">{navItems.map((item) => <a key={item.href} href={item.href} className={`nav-link ${active === item.href.slice(1) ? "active" : ""}`}>{item.label}</a>)}</nav><div className="flex items-center gap-2"><a href="#contact" className="header-cta hidden sm:inline-flex">Let&apos;s talk <ArrowUpRight size={14} /></a><ThemeToggle /><button onClick={() => setOpen(!open)} aria-label="Toggle navigation" className="icon-button md:hidden">{open ? <X size={18} /> : <Menu size={18} />}</button></div></div><AnimatePresence>{open && <motion.nav initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="mobile-menu md:hidden"><div className="mx-auto max-w-[1240px] px-5 pb-4 sm:px-8">{navItems.map((item) => <a onClick={() => setOpen(false)} key={item.href} href={item.href} className="mobile-link">{item.label}<ArrowUpRight size={14} /></a>)}</div></motion.nav>}</AnimatePresence></header>;
}

function ProjectLinks({ project }: { project: Project }) {
  if (!project.repository && !project.demo) return null;
  return <div className="project-links">{project.repository && <a href={project.repository} target="_blank" rel="noreferrer" className="project-link"><Github size={14} />Repository <ArrowUpRight size={12} /></a>}{project.demo && <a href={project.demo} target="_blank" rel="noreferrer" className="project-link project-link-accent">Live demo <ArrowUpRight size={12} /></a>}</div>;
}

function Capabilities() {
  return <section className="capability-section"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><div className="capability-intro"><div><p className="eyebrow"><span>↗</span>How I work</p><h2 className="font-display mt-4 max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Analysis first. Intelligence next.</h2></div><p className="max-w-md text-sm leading-7 text-muted">I connect careful data work with applied machine learning, so the output is both understandable and useful.</p></div></Reveal><div className="capability-grid">{focusAreas.map((area, index) => <Reveal key={area.title} delay={index * .06}><article className="capability-card"><div className="capability-number">0{index + 1}</div><p className="font-mono text-[10px] font-semibold uppercase tracking-[.16em] text-accent">{area.eyebrow}</p><h3 className="font-display mt-5 text-2xl font-semibold tracking-tight">{area.title}</h3><p className="mt-4 text-sm leading-7 text-muted">{area.copy}</p><div className="mt-6 flex flex-wrap gap-2">{area.tags.map((tag) => <span key={tag} className="tag">{tag}</span>)}</div></article></Reveal>)}</div></div></section>;
}

function ProjectModal({ project, onClose }: { project: Project; onClose: () => void }) {
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.body.style.overflow = "hidden"; window.addEventListener("keydown", onKey); return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", onKey); }; }, [onClose]);
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} className="modal-backdrop"><motion.div initial={{ opacity: 0, y: 18, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} onClick={(event) => event.stopPropagation()} className="modal-panel"><button onClick={onClose} aria-label="Close project details" className="icon-button absolute right-5 top-5"><X size={17} /></button><p className="eyebrow"><span>{project.number}</span>{project.type}</p><h3 className="font-display mt-5 max-w-xl pr-10 text-3xl font-semibold tracking-tight">{project.title}</h3><p className="mt-4 max-w-xl text-sm leading-7 text-muted">{project.description}</p>{project.image && <div className="relative mt-7 aspect-[16/8] overflow-hidden rounded-2xl border border-subtle"><Image src={project.image} alt={`${project.title} dashboard`} fill sizes="(max-width: 768px) 90vw, 650px" className="object-cover" /></div>}{project.metrics && <div className="mt-5 grid gap-2 sm:grid-cols-3">{project.metrics.map((metric) => <div key={metric} className="rounded-xl bg-accent-soft px-3 py-3 text-xs font-medium leading-5 text-accent">{metric}</div>)}</div>}{project.gallery && <div className="mt-3 grid grid-cols-3 gap-2">{project.gallery.map((image) => <div key={image} className="relative aspect-[4/3] overflow-hidden rounded-xl border border-subtle"><Image src={image} alt={`${project.title} visualization`} fill sizes="(max-width: 768px) 28vw, 200px" className="object-cover" /></div>)}</div>}<div className="mt-8 border-t border-subtle pt-6"><p className="eyebrow mb-5"><span>→</span>What it involved</p><ul className="space-y-4">{project.bullets.map((bullet) => <li key={bullet} className="flex gap-3 text-sm leading-6"><CheckCircle2 className="mt-1 shrink-0 text-accent" size={16} />{bullet}</li>)}</ul></div><div className="mt-8 flex flex-wrap items-center gap-2">{project.tags.map((tag) => <span key={tag} className="tag">{tag}</span>)}<ProjectLinks project={project} /></div></motion.div></motion.div>;
}

function Hero() {
  return <section className="hero-section"><div className="hero-grid" /><div className="mx-auto max-w-[1240px] px-5 pb-20 pt-28 sm:px-8 sm:pt-36 lg:pb-24"><div className="hero-layout"><Reveal className="relative z-10"><div className="hero-kicker"><span className="status-dot" />Data analytics <span>×</span> applied ML</div><p className="hero-identification">{profile.name} <span>/</span> {profile.roleLine}</p><h1 className="hero-title">I turn complex <em>data</em><br className="hidden sm:block" /> into useful systems<span>.</span></h1><p className="hero-summary">{profile.tagline} I build clear analysis, practical models, and end-to-end workflows that connect insight to action.</p><div className="mt-9 flex flex-wrap gap-3"><a href={profile.resume} download className="button button-primary">Download resume <Download size={16} /></a><a href="#projects" className="button button-secondary">See selected work <ArrowDownRight size={16} /></a></div><div className="hero-meta"><span><MapPin size={15} />{profile.location}</span><span><Sparkles size={15} />{profile.locationNote}</span></div></Reveal><Reveal delay={.12} className="relative z-10 mx-auto w-full max-w-[390px]"><div className="portrait-card"><div className="portrait-image"><Image src={profile.photo} alt={`${profile.name} portrait`} width={780} height={920} priority className="h-full w-full object-cover object-[center_24%]" /><div className="portrait-shade" /><div className="portrait-top"><span>PROFILE / 01</span><span className="live-dot" /></div><div className="portrait-bottom"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-white/60">Based in Pakistan</p><p className="mt-2 font-display text-3xl font-semibold tracking-tight text-white">Didar Ali<span className="text-accent-bright">.</span></p><p className="mt-2 text-sm text-white/65">Data analysis · Machine learning · Computer vision</p></div></div></div><div className="portrait-note"><span className="font-mono text-[10px] uppercase tracking-[.16em]">Open to relocation</span><ArrowUpRight size={16} /></div></Reveal></div><div className="hero-bottom"><div className="metric-strip">{profile.heroStats.map((stat) => <div key={stat.label} className="metric-item"><strong className="font-display">{stat.value}</strong><span>{stat.label}</span></div>)}</div><a href="#about" className="scroll-prompt">Scroll to explore <ArrowDownRight size={15} /></a></div></div></section>;
}

export default function Home() {
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const subject = encodeURIComponent(`Portfolio inquiry from ${data.get("name")}`); const body = encodeURIComponent(`${data.get("message")}\n\nReply to: ${data.get("email")}`); window.location.href = `mailto:${profile.email}?subject=${subject}&body=${body}`; setSent(true); };

  return <main id="top">
    <Header />
    <Hero />
    <Capabilities />
    <section id="about" className="section-wrap scroll-mt-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionIntro index="01" eyebrow="About" title="A bridge between analysis and engineering." copy="The strongest work usually happens between disciplines: asking a better question, building a cleaner pipeline, and explaining the result well." /></Reveal><div className="about-grid"><Reveal><div className="feature-panel about-panel h-full"><p className="max-w-2xl text-lg leading-8">{profile.summary}</p><div className="mt-10 grid gap-3 sm:grid-cols-3"><div className="mini-stat"><span className="text-accent">01</span><strong>Analytical</strong><p>SQL, Python, dashboards, and structured reporting.</p></div><div className="mini-stat"><span className="text-accent">02</span><strong>Model-aware</strong><p>ML, computer vision, OCR, NLP, and audio workflows.</p></div><div className="mini-stat"><span className="text-accent">03</span><strong>Clear-minded</strong><p>Readable outputs built for people, not just notebooks.</p></div></div></div></Reveal><Reveal delay={.08}><div className="about-aside"><p className="eyebrow eyebrow-light"><span>↗</span>Working principle</p><p className="about-quote">Good data work should make the next decision easier.</p><div className="about-aside-footer"><span>Python · SQL · ML</span><ArrowUpRight size={16} /></div></div></Reveal></div></div></section>
    <section id="experience" className="section-wrap section-tint scroll-mt-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionIntro index="02" eyebrow="Experience" title="Built close to the problem." copy="Hands-on work across document intelligence, identity verification, computer vision, and multi-stage AI validation." /></Reveal><div className="experience-card"><div className="experience-marker"><span>2026</span><i /></div>{experience.map((item) => <div key={item.company} className="experience-content"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-accent">{item.period}</p><h3 className="font-display mt-4 text-3xl font-semibold tracking-tight">{item.role}</h3><p className="mt-2 text-sm text-muted">{item.company} · {item.location}</p></div><span className="experience-label">AI ENGINEERING</span></div><ul className="experience-points">{item.points.map((point) => <li key={point}><Check size={15} />{point}</li>)}</ul></div>)}</div></div></section>
    <section id="projects" className="section-wrap scroll-mt-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionIntro index="03" eyebrow="Selected work" title="Work that moves from question to outcome." copy="A focused mix of analytics, research, applied machine learning, and interfaces that make technical work easier to use." /></Reveal><div className="project-grid">{projects.map((project, index) => <Reveal key={project.title} delay={index * .04} className={index === 0 ? "project-featured-wrap" : ""}><article className={`project-card group ${index === 0 ? "project-featured" : ""}`}>{project.image && <div className="project-cover"><Image src={project.image} alt={`${project.title} visualization`} fill sizes="(max-width: 768px) 90vw, 600px" className="object-cover transition duration-500 group-hover:scale-[1.04]" /><div className="project-cover-label">{project.imageLabel || "PROJECT ARTIFACT"} <ArrowUpRight size={14} /></div></div>}<div className="project-content"><div className="project-topline"><span className="font-mono text-xs text-accent">{project.number}</span><span className="font-mono text-[10px] uppercase tracking-[.16em] text-muted">{project.type}</span></div><h3 className="font-display mt-7 text-2xl font-semibold tracking-tight">{project.title}</h3><p className="mt-4 max-w-xl text-sm leading-7 text-muted">{project.description}</p><div className="mt-6 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="tag">{tag}</span>)}</div><div className="project-bottom"><p className="project-impact">{project.impact}</p><div className="flex flex-wrap items-center gap-3"><ProjectLinks project={project} /><button type="button" onClick={() => setSelectedProject(project)} className="text-link">Details <ChevronRight size={15} /></button></div></div></div></article></Reveal>)}</div></div></section>
    <section id="skills" className="section-wrap section-tint scroll-mt-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionIntro index="04" eyebrow="Toolkit" title="A practical stack for the full loop." copy="From querying and cleaning data to training models and packaging the result, these are the tools I use to move work forward." /></Reveal><div className="skills-grid">{skillGroups.map((group, index) => { const Icon = skillIcons[group.icon as keyof typeof skillIcons]; return <Reveal key={group.label} delay={index * .04}><div className="skill-card"><span className="skill-icon"><Icon size={19} /></span><h3 className="font-display mt-6 text-xl font-semibold">{group.label}</h3><div className="mt-5 flex flex-wrap gap-2">{group.items.map((item) => <span key={item} className="tag">{item}</span>)}</div></div></Reveal>; })}</div></div></section>
    <section className="section-wrap pt-0"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><div className="publication-panel"><div><p className="eyebrow eyebrow-light"><span>05</span>Publication</p><h2 className="font-display mt-5 max-w-2xl text-2xl font-semibold tracking-tight text-white sm:text-3xl">{publication.title}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/65">{publication.description}</p></div><div className="publication-meta"><span>{publication.publisher}</span><strong>{publication.year}</strong></div></div></Reveal></div></section>
    <section className="section-wrap border-t border-subtle"><div className="mx-auto grid max-w-[1240px] gap-14 px-5 sm:px-8 lg:grid-cols-2"><Reveal><p className="eyebrow"><span>06</span>Education</p><div className="mt-6 flex gap-4"><span className="skill-icon shrink-0"><GraduationCap size={20} /></span><div><h2 className="font-display text-2xl font-semibold tracking-tight">{education.degree}</h2><p className="mt-2 text-sm text-muted">{education.school} · {education.period}</p><span className="mt-5 inline-flex rounded-full border border-subtle px-3 py-1.5 font-mono text-xs text-muted">{education.result}</span></div></div></Reveal><Reveal delay={.08}><p className="eyebrow"><span>07</span>Certifications</p><div className="mt-6 space-y-3">{certifications.map((cert) => <div key={cert} className="flex items-center gap-3 rounded-xl border border-subtle bg-surface px-4 py-4 text-sm"><CheckCircle2 size={17} className="shrink-0 text-accent" />{cert}</div>)}</div></Reveal></div></section>
    <section id="contact" className="section-wrap contact-section scroll-mt-24"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><Reveal><p className="eyebrow"><span>08</span>Contact</p><h2 className="font-display mt-5 max-w-lg text-4xl font-semibold tracking-tight sm:text-5xl">Let&apos;s work on the useful part.</h2><p className="mt-5 max-w-md text-sm leading-7 text-muted">Have a dataset, product idea, or research question? Send a note and tell me what you&apos;re trying to understand or build.</p><div className="mt-8 space-y-4 text-sm"><a href={`mailto:${profile.email}`} className="contact-link"><Mail size={17} />{profile.email}</a><a href={`tel:${profile.phone.replaceAll(" ", "")}`} className="contact-link"><Phone size={17} />{profile.phone}</a></div><div className="mt-8 flex gap-2"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub" className="icon-button"><Github size={17} /></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" className="icon-button"><Linkedin size={17} /></a></div></Reveal><Reveal delay={.08}><form onSubmit={submit} className="contact-form"><div className="contact-form-heading"><span className="font-mono text-[10px] uppercase tracking-[.16em] text-accent">Start a conversation</span><span className="contact-form-index">08 / 08</span></div><div className="grid gap-5 sm:grid-cols-2"><label><span>Name</span><input required name="name" placeholder="Your name" /></label><label><span>Email</span><input required type="email" name="email" placeholder="you@example.com" /></label></div><label className="mt-5 block"><span>Message</span><textarea required name="message" rows={5} placeholder="What are you working on?" /></label><div className="mt-5 flex flex-wrap items-center gap-4"><button type="submit" className="button button-primary">{sent ? "Email draft ready" : "Send message"} <Send size={15} /></button>{sent && <span className="text-xs text-muted">Your email app should open with a draft.</span>}</div></form></Reveal></div></section>
    <footer className="site-footer"><div className="mx-auto flex max-w-[1240px] flex-col justify-between gap-4 px-5 py-7 text-xs text-muted sm:flex-row sm:items-center sm:px-8"><div><p>© {new Date().getFullYear()} {profile.name}</p><p className="mt-1 text-muted/70">Data analytics · Applied machine learning · Pakistan</p></div><a href="#top" className="text-link">Back to top <ArrowUpRight size={14} /></a></div></footer>
    <AnimatePresence>{selectedProject && <ProjectModal project={selectedProject} onClose={() => setSelectedProject(null)} />}</AnimatePresence>
  </main>;
}
